/* =========================================================
   LANA LANCHES
   BANCO DE DADOS
========================================================= */


/* =========================================================
   TABELA: CONFIGURAÇÃO DA LOJA
========================================================= */

create table if not exists store_settings (
  id integer primary key default 1,

  status text not null default 'closed'
    check (
      status in (
        'open',
        'paused',
        'closed'
      )
    ),

  updated_at timestamptz not null default now()
);


insert into store_settings (
  id,
  status
)
values (
  1,
  'closed'
)
on conflict (id)
do nothing;


/* =========================================================
   TABELA: PRODUTOS
========================================================= */

create table if not exists products (
  id bigint generated by default as identity primary key,

  category text not null,

  name text not null,

  description text,

  price numeric(10,2) not null
    check (price >= 0),

  active boolean not null default true,

  sort_order integer not null default 0
);


/* Impede produto duplicado */
create unique index if not exists
products_unique_name
on products(name);


/* =========================================================
   TABELA: BAIRROS
========================================================= */

create table if not exists neighborhoods (
  id bigint generated by default as identity primary key,

  name text not null unique,

  fee numeric(10,2) not null default 0
    check (fee >= 0),

  active boolean not null default true
);


/* =========================================================
   TABELA: PEDIDOS
========================================================= */

create table if not exists orders (
  id bigint generated by default as identity primary key,

  created_at timestamptz not null default now(),

  customer_name text not null,

  customer_phone text not null,

  fulfillment text not null
    check (
      fulfillment in (
        'delivery',
        'pickup'
      )
    ),

  neighborhood_id bigint
    references neighborhoods(id),

  street text,

  number text,

  complement text,

  payment_method text not null,

  notes text,

  subtotal numeric(10,2) not null,

  delivery_fee numeric(10,2) not null default 0,

  total numeric(10,2) not null,

  status text not null default 'received'
    check (
      status in (
        'received',
        'preparing',
        'ready',
        'delivering',
        'completed',
        'cancelled'
      )
    )
);


/* =========================================================
   TABELA: ITENS DO PEDIDO
========================================================= */

create table if not exists order_items (
  id bigint generated by default as identity primary key,

  order_id bigint not null
    references orders(id)
    on delete cascade,

  product_id bigint
    references products(id),

  name text not null,

  qty integer not null
    check (qty > 0),

  unit_price numeric(10,2) not null
);


/* =========================================================
   CARDÁPIO
========================================================= */


/* CACHORRO-QUENTE */

insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Cachorro-quente',
  'Cachorro Quente Simples',
  null,
  12,
  true,
  10
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Cachorro-quente',
  'Cachorro Quente Completo',
  null,
  14,
  true,
  20
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Cachorro-quente',
  'Cachorro Quente Especial',
  'Pão, salsicha, molho da casa, purê de batata, bacon, milho, vinagrete, queijo ralado e maionese.',
  16,
  true,
  30
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Cachorro-quente',
  'Cachorro Quente Duplo',
  null,
  18,
  true,
  40
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Cachorro-quente',
  'Cachorro Quente Duplo Bacon',
  null,
  20,
  true,
  50
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


/* =========================================================
   PASTÉIS
========================================================= */

insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Carne',
  null,
  12,
  true,
  110
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Carne com Queijo',
  null,
  15,
  true,
  120
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Carne com Catupiry',
  null,
  15,
  true,
  130
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Carne com Cheddar',
  null,
  15,
  true,
  140
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Pizza',
  null,
  12,
  true,
  150
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Bauru',
  null,
  12,
  true,
  160
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Calabresa com Queijo',
  null,
  12,
  true,
  170
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Frango com Catupiry',
  null,
  15,
  true,
  180
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Pastéis',
  'Pastel de Frango com Cheddar',
  null,
  15,
  true,
  190
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


/* =========================================================
   CALDOS
========================================================= */

insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Caldos',
  'Caldo de Quenga',
  null,
  16,
  true,
  210
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Caldos',
  'Caldo de Abóbora com Frango Desfiado',
  null,
  16,
  true,
  220
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Caldos',
  'Caldo Verde',
  null,
  16,
  true,
  230
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


/* =========================================================
   PORÇÕES
========================================================= */

insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Porções',
  'Batata Frita Pequena',
  null,
  15,
  true,
  310
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Porções',
  'Batata Frita Média',
  null,
  25,
  true,
  320
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Porções',
  'Batata Frita Grande',
  null,
  35,
  true,
  330
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


insert into products (
  category,
  name,
  description,
  price,
  active,
  sort_order
)
values (
  'Porções',
  'Porção de Calabresa',
  null,
  30,
  true,
  340
)
on conflict (name)
do update set
  category = excluded.category,
  description = excluded.description,
  price = excluded.price,
  sort_order = excluded.sort_order;


/* =========================================================
   ATIVAR RLS
========================================================= */

alter table store_settings
enable row level security;

alter table products
enable row level security;

alter table neighborhoods
enable row level security;

alter table orders
enable row level security;

alter table order_items
enable row level security;


/* =========================================================
   REMOVER POLICIES ANTIGAS
========================================================= */

drop policy if exists
"public read store"
on store_settings;

drop policy if exists
"public read products"
on products;

drop policy if exists
"public read neighborhoods"
on neighborhoods;

drop policy if exists
"public create orders"
on orders;

drop policy if exists
"public create order items"
on order_items;

drop policy if exists
"admin manage store"
on store_settings;

drop policy if exists
"admin manage products"
on products;

drop policy if exists
"admin manage neighborhoods"
on neighborhoods;

drop policy if exists
"admin read orders"
on orders;

drop policy if exists
"admin update orders"
on orders;

drop policy if exists
"admin read items"
on order_items;


/* =========================================================
   POLICIES PÚBLICAS
========================================================= */

create policy "public read store"
on store_settings
for select
to anon
using (true);


create policy "public read products"
on products
for select
to anon
using (true);


create policy "public read neighborhoods"
on neighborhoods
for select
to anon
using (true);


create policy "public create orders"
on orders
for insert
to anon
with check (true);


create policy "public create order items"
on order_items
for insert
to anon
with check (true);


/* =========================================================
   POLICIES ADMIN
========================================================= */

create policy "admin manage store"
on store_settings
for all
to authenticated
using (true)
with check (true);


create policy "admin manage products"
on products
for all
to authenticated
using (true)
with check (true);


create policy "admin manage neighborhoods"
on neighborhoods
for all
to authenticated
using (true)
with check (true);


create policy "admin read orders"
on orders
for select
to authenticated
using (true);


create policy "admin update orders"
on orders
for update
to authenticated
using (true)
with check (true);


create policy "admin read items"
on order_items
for select
to authenticated
using (true);
